# Generated by Django 4.1.4 on 2023-03-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cf_order_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
