# Generated by Django 4.1.4 on 2023-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_cf_order_id_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'TXN_SUCCESS'), (2, 'TXN_FAILURE'), (3, 'USER_DROPPED')], default=0),
        ),
    ]
