# Generated by Django 4.1.4 on 2023-03-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cf_payment_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
