# Generated by Django 4.1.4 on 2023-04-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_categorysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
