# Generated by Django 4.1.4 on 2023-04-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_product_id_payment_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySubscription',
        ),
    ]
