# Generated by Django 4.1.4 on 2023-04-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_categorysubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='CategorySubscription',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
