# Generated by Django 4.1.4 on 2023-04-19 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_post_order_no'),
        ('payments', '0010_remove_payment_user_delete_categorysubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'TXN_SUCCESS'), (2, 'TXN_FAILURE'), (3, 'USER_DROPPED')], default=0)),
                ('amount', models.FloatField()),
                ('cf_order_id', models.CharField(max_length=255, null=True)),
                ('cf_payment_id', models.CharField(max_length=255, null=True)),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('payment_session_id', models.CharField(max_length=255, null=True)),
                ('order_note', models.CharField(max_length=255, null=True)),
                ('product_type', models.CharField(max_length=255)),
                ('product_id', models.BigIntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='CategorySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.category')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category_subscriptions',
            },
        ),
    ]
