# Generated by Django 4.1.4 on 2023-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product_id',
            field=models.CharField(max_length=1000),
        ),
    ]
