# Generated by Django 4.1.4 on 2023-04-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='product_id',
            new_name='product_ids',
        ),
    ]
