# Generated by Django 4.1.4 on 2023-04-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_post_order_no'),
        ('payments', '0013_rename_product_id_payment_product_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category_payments',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product_ids',
        ),
        migrations.DeleteModel(
            name='CategorySubscription',
        ),
    ]
