# Generated by Django 4.1.4 on 2023-04-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_categorysubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysubscription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorysubscription',
            name='category_payment',
        ),
        migrations.RemoveField(
            model_name='categorysubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='CategoryPayment',
        ),
        migrations.DeleteModel(
            name='CategorySubscription',
        ),
    ]
