# Generated by Django 4.1.4 on 2023-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_paymentcategoryitem_categorysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategoryitem',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'TXN_SUCCESS'), (2, 'TXN_FAILURE'), (3, 'USER_DROPPED')], default=0),
        ),
    ]
