# Generated by Django 4.1.4 on 2023-04-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_paymentcategoryitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcategoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paymentcategoryitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='CategorySubscription',
        ),
        migrations.DeleteModel(
            name='PaymentCategoryItem',
        ),
    ]
