# Generated by Django 4.2.1 on 2023-06-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_remove_category_amount_remove_category_validity_and_more'),
        ('payments', '0020_paymentcategoryitem_categorysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategoryitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.course'),
        ),
    ]
