# Generated by Django 4.1.4 on 2023-01-03 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Video'), (3, 'Youtube'), (4, 'Instagram')], default=0)),
                ('attachment', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('status', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'short_posts',
            },
        ),
    ]
