# Generated by Django 4.1.4 on 2023-01-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortpost',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
