# Generated by Django 4.1.4 on 2023-01-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_shortpost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortpost',
            name='attachment',
        ),
        migrations.CreateModel(
            name='ShortPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(max_length=255, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.shortpost')),
            ],
            options={
                'db_table': 'short_post_attachments',
            },
        ),
    ]
