# Generated by Django 4.1.4 on 2023-01-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
