# Generated by Django 4.1.4 on 2023-02-11 04:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_category_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortPost',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='ShortPostAttachment',
            new_name='PostAttachment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='postattachment',
            table='post_attachments',
        ),
    ]
