# Generated by Django 4.1.4 on 2023-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_shortpost_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='postattachment',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Video'), (3, 'Youtube'), (4, 'Instagram')], default=0),
        ),
    ]
