# Generated by Django 4.1.4 on 2023-02-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_post_type_postattachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='premium',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.subcategory'),
        ),
    ]
