# Generated by Django 4.1.4 on 2023-02-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_category_post_featured_post_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
