# Generated by Django 4.1.4 on 2023-03-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_sub_category_category_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
