# Generated by Django 4.1.4 on 2023-04-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='premium',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='validity',
            field=models.IntegerField(default=0),
        ),
    ]
