# Generated by Django 4.1.4 on 2023-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_category_premium_category_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
