# Generated by Django 4.1.4 on 2023-04-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_category_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
