# Generated by Django 4.1.4 on 2023-05-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_post_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locked_text',
            field=models.TextField(null=True),
        ),
    ]
