# Generated by Django 4.2.1 on 2023-06-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_post_locked_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False)),
                ('name', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(max_length=255)),
                ('validity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('old_price', models.FloatField(default=0)),
                ('description', models.TextField(null=True)),
                ('what_included', models.TextField(null=True)),
                ('units', models.JSONField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
