# Generated by Django 4.2.1 on 2023-06-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_course_completed_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='completed_step',
            new_name='completed_step_no',
        ),
    ]
