# Generated by Django 4.2.1 on 2023-06-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_rename_completed_step_course_completed_step_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='validity',
        ),
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
