# Generated by Django 4.2.1 on 2023-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_remove_category_amount_remove_category_validity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
