# Generated by Django 4.2.1 on 2023-06-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_category_description_category_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
    ]
