# Generated by Django 4.2.1 on 2023-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_remove_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='categories/'),
        ),
    ]
