# Generated by Django 4.2.1 on 2023-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
