# Generated by Django 4.2.1 on 2023-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_category_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
