# Generated by Django 4.2.1 on 2023-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_alter_category_description_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
