# Generated by Django 4.2.1 on 2023-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_category_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='transcript',
            field=models.TextField(null=True),
        ),
    ]
