# Generated by Django 4.2.1 on 2023-07-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_category_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='transcript',
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='transcript',
            field=models.TextField(null=True),
        ),
    ]
