# Generated by Django 4.2.1 on 2023-07-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_postcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='order_no',
            new_name='post_order_no',
        ),
    ]
