# Generated by Django 4.2.1 on 2023-07-23 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_rename_order_no_postcategory_post_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='post.category'),
            preserve_default=False,
        ),
    ]
