# Generated by Django 4.2.1 on 2023-07-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='order_no',
        ),
    ]
