# Generated by Django 4.2.1 on 2023-07-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0039_remove_post_category_remove_post_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True),
        ),
    ]
