"""
Django settings for teachothers project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost','schoolistan.com','www.schoolistan.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'acc',
    'post',
    'storages',
    'payments',
    'utility',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_referrer_policy.middleware.ReferrerPolicyMiddleware',
]

ROOT_URLCONF = 'teachothers.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'teachothers.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('SC_DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        # 'PORT': '3306',
        # 'OPTIONS': {
        #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        # },
    }
}

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    url = urlparse(DATABASE_URL)
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": (url.path or "").lstrip("/"),
        "USER": url.username,
        "PASSWORD": url.password,
        "HOST": url.hostname,
        "PORT": str(url.port) if url.port else "",
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "600")),
        "OPTIONS": {"sslmode": "require"},
    }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Added Maually -------------------------------------------------------------------------------------
# setting for custom user model
AUTH_USER_MODEL = 'acc.User'  # should not remove in any case
LOGIN_URL = '/login'
ADMIN_LOGIN_URL = '/admin/login'

# REFERRER_POLICY
REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'


# settings for static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
    # '/var/www/static/',
]
# STATIC_ROOT = os.path.join(BASE_DIR, "static")

# setting for media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# """

# settings for aws bucket ---------------------
AWS_ACCESS_KEY_ID = os.environ.get('SK_AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('SK_AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'schoolistan-test'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
# AWS_LOCATION = 'static'
# STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

DEFAULT_FILE_STORAGE = 'teachothers.storage_backends.MediaStorage'
AWS_MEDIA_LOCATION = 'media'
MEDIA_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_MEDIA_LOCATION)

# """

MEDIA_LOCATION_S3 = True

# google login credentials
GOOGLE_LOGIN_CLIENT_ID = os.environ.get('SK_GOOGLE_LOGIN_CLIENT_ID')

# payment gateway (Razorpay)
# ("YOUR_ID", "YOUR_SECRET")
RAZORPAY_INFOS = (os.environ.get('RAZORPAY_ID'), os.environ.get('RAZORPAY_SECRET'))
WEBHOOK_SECRET = os.environ.get('WEBHOOK_SECRET')

# payment gateway (Cash free)
CASH_FREE_APP_ID = os.environ.get('SK_CASH_FREE_APP_ID')
CASH_FREE_SECRET_KEY = os.environ.get('SK_CASH_FREE_SECRET_KEY')
CASH_FREE_MODE = "sandbox"
# CASH_FREE_MODE = "production"

# VIMEO settings
VIMEO_ACCESS_TOKEN = os.environ.get('SK_VIMEO_ACCESS_TOKEN')
VIMEO_CLIENT_ID = os.environ.get('SK_VIMEO_CLIENT_ID')
VIMEO_CLIENT_SECRET = os.environ.get('SK_VIMEO_CLIENT_SECRET')

# setting for sending mail
EMAIL_BACKEND = 'django_ses.SESBackend'
EMAIL_HOST_USER = os.environ.get('SK_EMAIL_HOST_USER')
# AWS_SES_REGION_ENDPOINT = 'email.us-east-1.amazonaws.com'

# constants
ORDER_PRE_STR = "schoolistan_or_"

