# Generated by Django 4.1.4 on 2023-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_alter_contactus_name_alter_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='categories',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
