# Generated by Django 4.1.4 on 2023-05-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_post_locked_text'),
        ('home', '0003_banner_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.banner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
            options={
                'db_table': 'banner_categories',
            },
        ),
    ]
