# Generated by Django 4.1.4 on 2023-05-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_post_locked_text'),
        ('home', '0004_bannercategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerCategories',
            new_name='BannerCategory',
        ),
    ]
