# Generated by Django 4.1.4 on 2023-05-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_bannercategories_bannercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='categories',
        ),
    ]
