# Generated by Django 4.1.4 on 2023-01-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
