# Generated by Django 4.1.4 on 2023-02-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_user_social_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
