# Generated by Django 4.1.4 on 2023-03-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_user_dob_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_exp_date',
            field=models.DateField(null=True),
        ),
    ]
