# Generated by Django 4.1.4 on 2023-05-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_user_premium_exp_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500, null=True)),
                ('categories', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
