# Generated by Django 4.1.4 on 2023-05-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
