# Generated by Django 4.1.4 on 2023-05-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
