# Generated by Django 4.1.4 on 2023-05-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='categories',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
