# Generated by Django 4.1.4 on 2023-05-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0012_usercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='categories',
        ),
    ]
