# Generated by Django 4.2.1 on 2023-06-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0013_remove_userprofile_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
