# Generated by Django 4.2.1 on 2023-06-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0014_remove_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='premium_exp_date',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='user_pics/'),
        ),
    ]
